# Generated by Django 3.0.2 on 2020-03-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200311_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('last_time', models.DateTimeField()),
            ],
        ),
    ]
